version: '3'

volumes:
  pg_data_production:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ya0961/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
  frontend:
    env_file: .env
    image: ya0961/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      - media:/media
  gateway:
    image: ya0961/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static