version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ya0961/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
  frontend:
    image: ya0961/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: nginx
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media
      - ./config/nginx/conf.d:/etc/nginx/templates/
